### ISSUE TITLE
Invalid API endpoint for fetching gas estimate

### ISSUE THREAD

**Issue by Tranquil-Flow** [Montoya/gas-fee-snap#56]
Currently the readme advises to use: https://www.etherchain.org/api/gasPriceOracle which is no longer available and gives an 'unable to fetch' error. Recommend using https://beaconcha.in/api/v1/execution/gasnow, which is where you are redirected if navigating to https://etherchain.org/api/gasnow on browser.

**Comment by yashgoel72** [comment]
The issue is fixed now
